### PR TITLE
Be ready for tidyr v1.0.0

### PR DESCRIPTION
**Pull request by jennybc**
Main objective: get rid of the call to `tidyr::nest_()`. Secondary objective: write code that also works with CRAN tidyr.

Fixing the problems seen in our revdep checks:

https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#fuzzyjoin

This PR also works with CRAN tidyr, so you can submit now = in advance of tidyr.

### CODE REVIEW

**Comment by jennybc** [comment]
I am also preparing a second PR to clear a lot of warnings (not errors) and generally get more current with recent versions of dplyr and tidyr, FYI.

**Comment by dgrtwo** [comment]
Nice, thanks! To clarify, do you think I should accept + submit this to CRAN right away or wait on the second PR?

**Comment by jennybc** [comment]
Wait on the second PR. I think I'll finish this a.m.

**Comment by jennybc** [comment]
But you can merge this right away, if you're happy.

**Comment by dgrtwo** [comment]
Thanks!

**Pull request merged**
